# Generated by Django 4.1.7 on 2023-04-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0014_remove_rdv_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='Problème',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
