# Generated by Django 4.1.7 on 2023-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0024_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.CharField(default='   ', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Sujet',
            field=models.CharField(max_length=30),
        ),
    ]
