# Generated by Django 4.1.7 on 2023-05-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docsiteapp', '0025_contact_message_alter_contact_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='signin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signin',
            name='Mot_De_Passe3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='signin',
            name='Nom_Utilisateur2',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
