# Generated by Django 4.1.7 on 2023-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0026_signin_user_alter_signin_mot_de_passe3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='user',
        ),
        migrations.AlterField(
            model_name='signin',
            name='Mot_De_Passe3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='signin',
            name='Nom_Utilisateur2',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
