# Generated by Django 4.1.7 on 2023-05-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0029_remove_signin_user_alter_signin_mot_de_passe3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='Vet',
            field=models.CharField(choices=[('', 'choisissez un vétérinaire'), ('1', 'inesarfa'), ('2', 'sofieneelali'), ('3', 'mariemayed'), ('4', 'Rachedhajar'), ('5', 'Ferdawshanbouli'), ('6', 'Ranimeelhkir'), ('7', 'saberbouhada'), ('8', ' amenibilhaj')], max_length=1),
        ),
    ]
