# Generated by Django 4.1.7 on 2023-04-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Téléphone', models.CharField(max_length=30)),
                ('Vet', models.CharField(max_length=30)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
