# Generated by Django 4.1.7 on 2023-04-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0016_rdv_pet_rdv_prénom_alter_rdv_vet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='Prénom',
            new_name='Prenom',
        ),
    ]
