# Generated by Django 4.1.7 on 2023-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0017_rename_prénom_rdv_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='Prenom',
            new_name='Prénom',
        ),
    ]
