# Generated by Django 4.1.7 on 2023-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0019_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Mot_De_Passe2',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
