# Generated by Django 4.1.7 on 2023-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0021_alter_signup_mot_de_passe_alter_signup_mot_de_passe2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Utilisateur2', models.CharField(default='', max_length=30, unique=True)),
                ('Mot_De_Passe3', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
