# Generated by Django 4.1.7 on 2023-04-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsiteapp', '0022_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
