# Generated by Django 4.1.7 on 2023-05-06 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docsiteapp', '0030_alter_rdv_vet'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='', max_length=40)),
                ('Prénom', models.CharField(default='', max_length=40)),
                ('Email', models.EmailField(max_length=100)),
                ('Sujet', models.CharField(default='', max_length=40)),
                ('Message', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='', max_length=30)),
                ('Prénom', models.CharField(default='', max_length=30)),
                ('Nom_Utilisateur', models.CharField(default='', max_length=30, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mot_De_Passe', models.CharField(default='', max_length=30)),
                ('Mot_De_Passe2', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='Prénom',
        ),
        migrations.AddField(
            model_name='rdv',
            name='Prenom',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='signin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='Nom',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='Pet',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='Service',
            field=models.CharField(blank=True, choices=[('', 'choisissez votre service'), ('1', 'Consultation'), ('2', 'Vaccinations'), ('3', 'Micropuçage'), ('4', 'Pension'), ('5', 'Soins Dentaires'), ('6', 'Toilettage')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='Téléphone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='Vet',
            field=models.CharField(blank=True, choices=[('', 'choisissez votre vétérinaire'), ('1', 'inesarfa'), ('2', 'sofieneelali'), ('3', 'mariemayed'), ('4', 'Rachedhajar'), ('5', 'Ferdawshanbouli'), ('6', 'Ranimeelhkir'), ('7', 'saberbouhada'), ('8', 'amenibilhaj')], max_length=1, null=True),
        ),
    ]
